version: "3.7"

services:
  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - dabin_network
    volumes:
      - /home/kangdb123-/nginx.conf:/etc/nginx/nginx.conf
      - dabin_static:/data/static/
      - dabin_media:/data/media/

  django:
    image: dabin_django:3
    networks:
      - dabin_network
    volumes:
      - dabin_static:/home/gis_web_1/staticfiles/
      - dabin_media:/home/gis_web_1/media/


networks:
  dabin_network:

volumes:
  dabin_static:
  dabin_media: